### ISSUE TITLE
[question]: Search Functionality

### ISSUE THREAD

**Issue by Zolive** [jgazeau/shadocs#227]
### Question?

Hello, in first thank you for this great theme. I just discovered it, and it answers to my needs :)

It's seems that **Search functionality** does not run in my project (not published yet on Internet).

- Shadoc site, *Search Functionality* is **OK**.
- Once theme installed, Exemple Site ran locally `hugo -s exampleSite/ server` *Serach Functionality* is **KO (fresh install)** no modifications on hugo.toml file done.
- On my project *Search Functionality* is **KO**
- All other functionalities are running well : intro, print, shortcuts (except search), info....

Please below my hugo.toml ; i did not updated or replaced any themeParams.toml in theme/shadocs/data/themeParams.toml

Did I make a configuration error ?

Thank you in advance.

My hugo.toml

```ksh
defaultContentLanguage` = "fr"
metaDataFormat         = "yaml"
title                  = "0liv's blog"
theme                  = "shadocs"

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "JSON"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    ordered    = false
    startLevel = 1 # start level for toc
    endLevel   = 6 # end level for toc
  [markup.goldmark.renderer]
    unsafe = false

[Languages]
  [Languages.fr]
    contentDir   = "content/fr"
    title        = "Le blog de 0liv"
    weight       = 1
    languageName = "Français"

  [Languages.en]
    contentDir   = "content/en"
    title        = "0liv's blog"
    weight       = 2
    languageName = "English"

[params]
  logo                    = "images/logo.png"
  logoTouch               = "images/logoTouch.png"
  image404                = "images/404.gif"
  favicon                 = "images/favicon.png"
  faviconmd               = "![Favicon](/images/favicon.png)"
  homeLayout              = "onboarding"
  siteContentOrder        = "weight"
  toc                     = true
  enforceRefrelLinks      = true

  [params.taxonomies]
    [params.taxonomies.categories]
      icon = "fa-solid fa-table-cells"
    [params.taxonomies.tags]
      icon = "fa-solid fa-tag"
```

![SearchUnavailable](https://github.com/jgazeau/shadocs/assets/4532793/8205f0da-f928-459a-a045-83541be603ab)

**Comment by jgazeau** [comment]
Hi @Zolive and sorry for the delay.
This is actually quite strange because the `exampleSite` is definitely working on the repo on the main branch.
Which version of hugo are you using ? (At least the 0.112.0-extended is needed).

The  `Non disponible` title error actually induce the file index.json which contains the static search extract cannot be found.
What I suggest is to build the generate the website (`hugo -s exampleSite/`) files and check if the `/index.json` file exist and contains appropriate data:
For exempleSite you should have this:
![image](https://github.com/jgazeau/shadocs/assets/45284640/30f15e94-d85c-404a-b4ba-14b4a2f657ef)
![image](https://github.com/jgazeau/shadocs/assets/45284640/d55a77f5-d560-45f4-a504-681a868ab19f)

If you don't have this file maybe try to use another version of Hugo (For the record I'm using the 0.112.5-extended version) and check the debug mode if you found something during file generation

**Comment by Zolive** [comment]
Hello Jojo,

thanks for your feedback, sorry for the delay.

Please find information regarding the environment:

- Operating Sytem : OpenBSD-current (7.4)
- http server: [httpd server](https://github.com/reyk/httpd) by reyk floeter
- hugo version: hugo v0.121.1+extended openbsd/amd64 BuildDate=unknown

In fact all is running fine.

ROOT CAUSE : It seems that i forget to adapt the configuration for my local web server.

- I tested locally via IP address and not FQDN... once configuration updated in this way... All is running fine.
- I apologize for the noise.

Thank you for your help and answers.

Z0liv.
![blok_OK](https://github.com/jgazeau/shadocs/assets/4532793/20a68994-dc0b-4d75-ab2b-eb3b18cafc29)
