### ISSUE TITLE
Error building site

### ISSUE THREAD

**Issue by pensivedog** [jgazeau/shadocs#62]
Any ideas what could be causing this error and how to resolve it?

Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:1:2: executing "_default/single.html" at <partial "main.html" (dict "root" . "contentTemplate" "theme/content.html")>: error calling partial: execute of template failed: template: partials/main.html:4:4: executing "partials/main.html" at <partial "theme/includes-head.html" .root>: error calling partial: "G:\me\themes\shadocs\layouts\partials\theme\includes-head.html:21:10": execute of template failed: template: partials/theme/includes-head.html:21:10: executing "partials/theme/includes-head.html" at <.>: range can't iterate over css/shortcuts.css

**Comment by jgazeau** [comment]
Hello @pensivedog ,
Can you provide more context regarding your issue ?
* what command did you use ?
* did you follow the [installation part](https://shadocs.netlify.app/theme/introduction/#installation) of the documentation ?
* which version of Hugo are you using ?

**Comment by pensivedog** [comment]
Thanks for the reply and for your work on this wonderful theme.

I'm using the R blogdown package for the installation, which runs Hugo version 0.98.0.

All the assets mentioned in the installation part of the documentation are successfully added, except for Bulma, which I had to download and add separately.

Any ideas?

**Comment by jgazeau** [comment]
Thanks, I'm glad you appreciate it 😃 
I've never heard about the R blogdown so not sure I'll be able to help you on that part. 
Nevertheless, I think the problem is just regarding the git submodule that I used for bulma. By default git doesn't checkout submodules, so you'll have to do it by yourself.
After checking on the R blogdown doc it seems that there is a section that might help you: https://bookdown.org/yihui/blogdown/version-control.html

**Comment by pensivedog** [comment]
I'm not using version control in my project at this point. Still just trying to get shadocs up and running. A few other hugo themes I've tested have built fine with blogdown. I'm not so concerned about bulma not importing, which doesn't seem to be the cause of the error mentioned in the OP. Any other ideas on how I might troubleshoot that?

**Comment by yihui** [comment]
@pensivedog Currently `blogdown::new_site()` and `blogdown::install_theme()` do not support themes that use submodules because Github doesn't include submodules when we download a repo as a zip archive: https://github.com/dear-github/dear-github/issues/214 I can consider adding the support in blogdown, but it will require you to have Git installed first. For now, I think the easiest way for you is to download the submodule `bulma` manually: https://github.com/jgazeau/shadocs/tree/main/assets ([link to zip](https://github.com/jgthms/bulma/archive/4508573d932670ff922280a2f6fbf2a3851c20b1.zip)) and unzip the files to the `themes/shadocs/assets/bulma` directory of your website project.

**Comment by jgazeau** [comment]
Thanks for your answer @yihui .
Indeed @pensivedog for your case, because you are not relying on git, you will need to download bulma manually.

**Comment by pensivedog** [comment]
@yihui Thank you for the reply! I had already downloaded and added bulma prior to opening this issue. Those files not being there caused a different error:

Error: Error building site: TOCSS: failed to transform "css/main.sass" (text/x-sass): SCSS processing failed: file "stdin", line 3, col 1: File to import not found or unreadable: bulma.

Once the bulma files are in place, the error changes to the one in the original post.

I apologize for persisting with this... am I missing something?

**Comment by jgazeau** [comment]
@pensivedog , can you provide a reproducer so I can help you ?
The error actually refer to an array problem in the configuration. To include assets files in the html you can be declare all the files within the `params.includes` section. But they have to be declared as an array.
As an example here is the [config.toml](https://github.com/jgazeau/shadocs/blob/main/exampleSite/config.toml) used for the example (shadocs) website

**Comment by pensivedog** [comment]
The only way I know how to reproduce this error is in RStudio as per the blogdown documentation [quick setup guide](https://bookdown.org/yihui/blogdown/a-quick-example.html#create-project):

1. Create a new project and specify jgazeau/shadocs for the theme
2. Download bulma and place the files in themes/shadocs/assets/bulma/
3. Serve site via blogdown::serve_site()

The project's config.yaml file seems to accurately reflect the content of the Shadocs example site config.toml file.

Thank you again for your help and my apologies for my limited ability to troubleshoot this myself, as I'm not a web developer.

**Comment by yihui** [comment]
@pensivedog Open `config.yaml` and change `css/shortcuts.css` to `[css/shortcuts.css]`, and `js/shortcuts.js` to `[js/shortcuts.js]` (this is probably a **blogdown** bug when converting TOML to YAML; I'll see). Then you have to initialize `git` for your website project (`git init` and at least commit once). After that, you should be able to preview your site with `blogdown::serve_site()`.

**Comment by pensivedog** [comment]
@yihui Problem solved! Thank you for helping and for all your brilliant work on blogdown!

**Comment by jgazeau** [comment]
Perfect and thanks @yihui for the help :). 
I'll try to check blogdown and also enhance the shadocs documentation to explain how to install the theme with it.
